### PR TITLE
added English names for provinces in China

### PR DESCRIPTION
**Pull request by coachwei**

### CODE REVIEW

**Comment by coachwei** [comment]
Added English names for provinces in China, as well as "alt" names for some of them in English.

**Comment by coachwei** [comment]
added "Washington DC" and "Washington D.C." as "alt" names for "District of Columbia"

**Comment by coachwei** [comment]
Fixed two typos: "Heibei" should be "Hebei" and "Heinan" should be "Henan"

**Comment by jorrit** [comment]
Perhaps the key should be `latinized` or something like that.

**Comment by coachwei** [comment]
what does "Perhaps the key should be latinized or something like that" mean?

**Comment by jorrit** [comment]
What I meant is that the names you gave aren't necessarily English, they are the latinized versions of the Chinese names. My suggestion was to make the JSON key `latinized` instead of `english`. But now I see that other provinces that have names in a different alphabet also use the JSON key `english`, so my suggestion is invalid.

**Comment by coachwei** [comment]
@jorrit, the names I gave are the English names - meaning these names would be how a non-chinese speaking person refer to these provinces. If you search on these Chinese provinces on Google using English, you will see these names displayed. Thanks.

**Comment by zeke** [comment]
```
~/forks/provinces master
❯ np minor
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies using npm
 ✔ Running tests
 ✔ Bumping version
 ✔ Publishing package
 ✔ Pushing tags

 provinces 1.11.0 published 🎉
```

**Pull request merged**
